Repository jenkinsci/role-strategy-plugin, pull requests merged in 2019-07, with the labels that each got.

#83 [JENKINS-58399] Performance: Avoid finding implying permissions on each `hasPermission()` call
  src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleMap.java
  src/main/java/org/jenkinsci/plugins/rolestrategy/permissions/DangerousPermissionHandlingMode.java
  src/main/java/org/jenkinsci/plugins/rolestrategy/permissions/PermissionHelper.java
  src/test/java/org/jenkinsci/plugins/rolestrategy/DangerousPermissionsTest.java
Labels: enhancement

#90 Role-Based Project Naming Strategy: Do not iterate through roles for blank names
  src/main/java/org/jenkinsci/plugins/rolestrategy/RoleBasedProjectNamingStrategy.java
Labels: enhancement

#92 Release Drafter: Add release name to the template
  .github/release-drafter.yml
Labels: internal

#93 Move Documentation from Wiki to GitHub
  README.md
  docs/MACROS.md
  docs/USERSCRIPTS.md
  docs/images/.keepit
  docs/images/assignRoles.png
  docs/images/configureSecurity.png
  docs/images/jenkins-userscripts.png
  docs/images/macroDefinition.PNG
  docs/images/manageAndAssignRoles.png
  docs/images/manageRoles.png
  docs/images/role-strategy-ui-enhancer.png
Labels: documentation

#95 Delete the obsolete CONTRIBUTORS file
  CONTRIBUTORS
Labels: internal

#96 Enable Java 11 tests in the pull request builder
  Jenkinsfile
Labels: tests

#97 Enable Dependabot to keep development tools up to date
  .dependabot/config.yml
Labels: internal

#99 Cleanup whitespaces in the code
  src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/Role.java
  src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java
  src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleMap.java
  src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig.java
  src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/IMacroExtension.java
  src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/Macro.java
  src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/MacroException.java
  src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/RoleType.java
  src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/UserMacroExtension.java
  src/main/java/org/jenkinsci/plugins/rolestrategy/Settings.java
  src/main/java/org/jenkinsci/plugins/rolestrategy/permissions/DangerousPermissionAdministrativeMonitor.java
  src/main/java/org/jenkinsci/plugins/rolestrategy/permissions/DangerousPermissionHandlingMode.java
  src/main/java/org/jenkinsci/plugins/rolestrategy/permissions/PermissionHelper.java
Labels: internal
