Repository jenkinsci/role-strategy-plugin, pull requests merged in 2019-10, with the labels that each got.

#94 [JENKINS-58536] Remove dependency on deprecated jquery-ui plugin
  pom.xml
  src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java
  src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-project-roles.jelly
  src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-roles.jelly
  src/main/webapp/css/role-strategy.css
Labels: dependencies

#106 Use more common MIT license URL
  pom.xml
Labels: chore

#107 Adjust the GitHub Releases badge text to avoid confusion with the plugin site badge
  README.md
Labels: documentation
