Repository jenkinsci/role-strategy-plugin, pull requests merged in 2019-12, with the labels that each got.

#110 [JENKINS-43058] - Replace obsolete slave/project terms in UI (part 2)
  src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-roles.jelly
Labels: enhancement

#112 [JENKINS-56391] Trim whitespace from user/groups when assigning roles
  src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java
  src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/Messages.properties
  src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-global-roles.jelly
  src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-project-roles.jelly
  src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-slave-roles.jelly
Labels: enhancement

#116 Cleanup old code
  pom.xml
  src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleMap.java
  src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig.java
  src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/UserMacroExtension.java
  src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/macros/StubMacro.java
  src/main/java/org/jenkinsci/plugins/rolestrategy/permissions/PermissionHelper.java
  src/test/java/org/jenkinsci/plugins/rolestrategy/RoleAssignmentTest.java
  src/test/java/org/jenkinsci/plugins/rolestrategy/UserAuthoritiesAsRolesTest.java
Labels: chore

#115 Cache Role Macros to improve the permission check performance
  src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/RoleMacroExtension.java
Labels: enhancement

#114 Prevent errors when saving Role Strategy configurations after being configured with unmodifyable collections by JCasC
  src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleMap.java
Labels: bug
