Repository jenkinsci/role-strategy-plugin, pull requests merged in 2019-05, with the labels that each got.

#64 Cleanup the readme page
  LICENSE.md
  README.md
Labels: documentation

#65 [JENKINS-57425] Run benchmarks only when a special Maven profile is defined
  Jenkinsfile
  pom.xml
  src/test/java/jmh/BenchmarkRunner.java
Labels: internal

#66 Add a benchmark for creation of ACL objects
  src/test/java/jmh/benchmarks/CascBenchmark.java
Labels: internal

#60 [JENKINS-53931] - Provide JCasC compatibility inside the plugin, Configuration as Code: Support plugin is no longer needed for it
  .mvn/extensions.xml
  .mvn/maven.config
  pom.xml
  src/main/java/org/jenkinsci/plugins/rolestrategy/casc/GrantedRoles.java
  src/main/java/org/jenkinsci/plugins/rolestrategy/casc/PermissionFinder.java
  src/main/java/org/jenkinsci/plugins/rolestrategy/casc/RoleBasedAuthorizationStrategyConfigurator.java
  src/main/java/org/jenkinsci/plugins/rolestrategy/casc/RoleDefinition.java
  src/test/java/org/jenkinsci/plugins/rolestrategy/PermissionAssert.java
  src/test/java/org/jenkinsci/plugins/rolestrategy/RoleStrategyTest.java
  src/test/resources/org/jenkinsci/plugins/rolestrategy/Configuration-as-Code-Export.yml
  src/test/resources/org/jenkinsci/plugins/rolestrategy/Configuration-as-Code.yml
  src/test/resources/org/jenkinsci/plugins/rolestrategy/Configuration-as-Code2.yml
Labels: enhancement

#67 Add a benchmark for RoleMap#hasPermission
  src/test/java/jmh/BenchmarkRunner.java
  src/test/java/jmh/benchmarks/RoleMapBenchmark.java
Labels: internal

#69 [JENKINS-57730] Automatically detect JMH benchmark classes
  pom.xml
  src/test/java/jmh/BenchmarkFinder.java
  src/test/java/jmh/BenchmarkRunner.java
  src/test/java/jmh/JmhBenchmark.java
  src/test/java/jmh/benchmarks/CascBenchmark.java
  src/test/java/jmh/benchmarks/PermissionBenchmark.java
  src/test/java/jmh/benchmarks/RoleMapBenchmark.java
Labels: internal
