Repository jenkinsci/role-strategy-plugin, pull requests merged in 2019-06, with the labels that each got.

#70 Add hasPermission benchmarks for 100, 200 and 500 roles
  src/test/java/jmh/benchmarks/PermissionBenchmark.java
  src/test/java/jmh/benchmarks/RoleMapBenchmark.java
Labels: internal

#73 Add support of WebClient-based tests for REST API and Web UI benchmarks
  src/test/java/jmh/JmhJenkinsRule.java
  src/test/java/jmh/benchmarks/WebClientBenchmark.java
Labels: tests

#76 Update MaliciousRegexBenchmark to compare page render times and time to check READ permission
  src/test/java/jmh/JmhJenkinsRule.java
  src/test/java/jmh/benchmarks/MaliciousRegexBenchmark.java
  src/test/java/jmh/benchmarks/WebClientBenchmark.java
Labels: tests

#77 Add new benchmark for RoleMap#newMatchingRoleMap
  src/test/java/jmh/benchmarks/FolderAccessBenchmark.java
Labels: tests

#80 Bump up Plugin POM to 3.46
  pom.xml
  src/test/java/jmh/BenchmarkRunner.java
Labels: dependencies

#82 Update test dependencies to Configuration-as-Code plugin 1.21
  pom.xml
  src/test/java/jmh/benchmarks/CascBenchmark.java
  src/test/java/jmh/casc/CascJmhBenchmarkState.java
  src/test/resources/jmh/benchmarks/sample-casc.yml
Labels: dependencies

#84 Add Release reference badges to the README
  README.md
Labels: documentation

#81 Performance: Cache RoleMaps produced by `RoleMap#newMatchingRoleMap()`
  src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleMap.java
Labels: enhancement

#85 Refactor RoleBasedAuthorizationStrategy to use Enum keys
  src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java
Labels: enhancement

#88 Create a developer documentation page
  README.md
  docs/DEVELOPER.md
Labels: documentation
