Repository jenkinsci/role-strategy-plugin, pull requests merged in 2020-10, with the labels that each got.

#143 Update configurations in the CI pipeline, temporarily disable benchmarks
  Jenkinsfile
Labels: internal

#139 Remove strict dependency on Extended Read Permission plugin
  pom.xml
  src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig.java
Labels: enhancement

#142 [JENKINS-61470, JENKINS-61508] Invalidate cache for assign and unassign
  src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleMap.java
  src/test/java/com/michelin/cio/hudson/plugins/rolestrategy/APITest.java
Labels: major-bug

#145 Hacktoberfest - Rename jenkins/jnlp-slave -> jenkins/inbound-agent
  src/test/performance/init_scripts/src/main/groovy/scripts/Docker.groovy
Labels: chore, hacktoberfest-accepted
