Repository jenkinsci/role-strategy-plugin, pull requests merged in 2021-05, with the labels that each got.

#159 Use bom to manage dependencies
  pom.xml
Labels: dependencies

#152 add code usage for groovy hook script/jenkins script console.
  README.md
Labels: documentation

#157 Remove usage of guava from the plugin
  src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java
  src/test/java/jmh/benchmarks/FolderAccessBenchmark.java
Labels: chore

#151 Support UTF-8 charset in the /strategy/getMatchingJobs API
  src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java
Labels: enhancement
