Repository jenkinsci/role-strategy-plugin, pull requests merged in 2022-05, with the labels that each got.

#173 Enable CD
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .mvn/maven.config
  pom.xml
Labels: enhancement

#172 Remove dependency to matrix-auth plugin
  pom.xml
  src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java
  src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/ValidationUtil.java
  src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-global-roles.jelly
  src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-project-roles.jelly
  src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-slave-roles.jelly
  src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-roles.jelly
Labels: major-bug

#174 Update bom
  .github/dependabot.yml
  pom.xml
Labels: dependencies

#175 Test building on Java 17
  Jenkinsfile
Labels: chore

#180 feat: Update header icons
  src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-roles.jelly
  src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/index.jelly
  src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/list-macros.jelly
  src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-roles.jelly
Labels: enhancement

#178 [JENKINS-67456] add check that pattern is valid
  src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleBasedAuthorizationStrategy.java
  src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-project-roles.jelly
  src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-roles.jelly
  src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/manage-slave-roles.jelly
Labels: bug
