Repository jenkinsci/role-strategy-plugin, pull requests merged in 2023-08, with the labels that each got.

#324 [JENKINS-51672][JENKINS-41731] get users role in pipeline
  README.md
  pom.xml
  src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleMap.java
  src/main/java/org/jenkinsci/plugins/rolestrategy/pipeline/AbstractUserRolesStep.java
  src/main/java/org/jenkinsci/plugins/rolestrategy/pipeline/UserGlobalRoles.java
  src/main/java/org/jenkinsci/plugins/rolestrategy/pipeline/UserItemRoles.java
  src/main/resources/org/jenkinsci/plugins/rolestrategy/pipeline/UserGlobalRoles/help.html
  src/main/resources/org/jenkinsci/plugins/rolestrategy/pipeline/UserItemRoles/config.jelly
  src/main/resources/org/jenkinsci/plugins/rolestrategy/pipeline/UserItemRoles/help-showAllRoles.html
  src/main/resources/org/jenkinsci/plugins/rolestrategy/pipeline/UserItemRoles/help.html
  src/test/java/org/jenkinsci/plugins/rolestrategy/pipeline/UserGlobalRolesTest.java
  src/test/java/org/jenkinsci/plugins/rolestrategy/pipeline/UserItemRolesTest.java
  src/test/resources/org/jenkinsci/plugins/rolestrategy/pipeline/Configuration-as-Code-pipeline.yml
Labels: enhancement

#325 [JENKINS-71772] Remove runtime dependency on authorize-project plugin
  pom.xml
Labels: bug, dependencies

#326 Use plugin bom for dependency version definitions
  pom.xml
Labels: dependencies

#330 Test on Java 21
  Jenkinsfile
Labels: chore

#331 make delete symbols less prominent
  src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/assign-roles.jelly
  src/main/resources/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig/index.jelly
Labels: chore

#332 [JENKINS-19409] use idstrategy to match role assignments
  README.md
  src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleMap.java
  src/test/java/org/jenkinsci/plugins/rolestrategy/RoleStrategyTest.java
  src/test/resources/org/jenkinsci/plugins/rolestrategy/RoleStrategyTest/config.xml
Labels: bug, breaking
