Repository jenkinsci/role-strategy-plugin, pull requests merged in 2023-01, with the labels that each got.

#265 Revert "Forward compatibility with jenkins-buttons"
  src/main/resources/org/jenkinsci/plugins/rolestrategy/NamingStrategyAdministrativeMonitor/message.jelly
Labels: enhancement

#264 [JENKINS-62124] NPE when exporting role without permissions with casc
  src/main/java/org/jenkinsci/plugins/rolestrategy/permissions/PermissionHelper.java
  src/test/java/org/jenkinsci/plugins/rolestrategy/ConfigurationAsCodeTest.java
  src/test/resources/org/jenkinsci/plugins/rolestrategy/Configuration-as-Code-no-permissions-export.yml
  src/test/resources/org/jenkinsci/plugins/rolestrategy/Configuration-as-Code-no-permissions.yml
Labels: bug

#259 delete performance folder
  src/test/performance/Dockerfile
  src/test/performance/LICENSE.md
  src/test/performance/Makefile
  src/test/performance/README.md
  src/test/performance/init_scripts/pom.xml
  src/test/performance/init_scripts/src/main/groovy/GroovyBootstrap.groovy
  src/test/performance/init_scripts/src/main/groovy/demo/README.md
  src/test/performance/init_scripts/src/main/groovy/demo/jenkins-buildPlugin.groovy
  src/test/performance/init_scripts/src/main/groovy/io/jenkins/systemgroovy/plugins/PipelineHelper.groovy
  src/test/performance/init_scripts/src/main/groovy/scripts/Auth.groovy
  src/test/performance/init_scripts/src/main/groovy/scripts/Docker.groovy
  src/test/performance/init_scripts/src/main/groovy/scripts/MasterComputer.groovy
  src/test/performance/init_scripts/src/main/groovy/scripts/ProductionFolder.groovy
  src/test/performance/init_scripts/src/main/groovy/scripts/SystemFolder.groovy
  src/test/performance/init_scripts/src/main/groovy/scripts/Tools.groovy
  src/test/performance/init_scripts/src/main/groovy/scripts/Views.groovy
  src/test/performance/jenkins.yaml
  src/test/performance/jenkins2.sh
  src/test/performance/plugins.txt
  src/test/performance/pom.xml
Labels: internal

#268 Update javadoc
  src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleMap.java
  src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/macros/ContainedInViewMacro.java
Labels: documentation

#269 Code enhancements
  src/main/java/com/michelin/cio/hudson/plugins/rolestrategy/RoleStrategyConfig.java
  src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/macros/ContainedInViewMacro.java
  src/main/java/com/synopsys/arc/jenkins/plugins/rolestrategy/macros/FolderMacro.java
  src/main/java/org/jenkinsci/plugins/rolestrategy/RoleBasedProjectNamingStrategy.java
  src/main/java/org/jenkinsci/plugins/rolestrategy/permissions/PermissionHelper.java
  src/test/java/org/jenkinsci/plugins/rolestrategy/AuthorizeProjectTest.java
Labels: internal

#267 Update to Jenkins 2.361.4 LTS
  Jenkinsfile
  pom.xml
Labels: chore
